using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AvaloniaDraft.ComparingMethods;


/// <summary>
/// Contains the script code for each language.
/// From: https://stackoverflow.com/a/17755855 
/// </summary>
public static class ScriptCodes
{
    public static readonly ImmutableDictionary<string, Dictionary<string, string>> Scripts = new Dictionary<string, Dictionary<string, string>>() {
            { "aa", new Dictionary<string, string> { { "", "Latn"} } },
            { "ab", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "abq", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "ace", new Dictionary<string, string> { { "", "Latn"} } },
            { "ach", new Dictionary<string, string> { { "", "Latn"} } },
            { "ada", new Dictionary<string, string> { { "", "Latn"} } },
            { "ady", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "ae", new Dictionary<string, string> { { "", "Avst"} } },
            { "af", new Dictionary<string, string> { { "", "Latn"} } },
            { "agq", new Dictionary<string, string> { { "", "Latn"} } },
            { "aii", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "ain", new Dictionary<string, string> { { "", "Kana"} } },
            { "ak", new Dictionary<string, string> { { "", "Latn"} } },
            { "akk", new Dictionary<string, string> { { "", "Xsux"} } },
            { "ale", new Dictionary<string, string> { { "", "Latn"} } },
            { "alt", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "am", new Dictionary<string, string> { { "", "Ethi"} } },
            { "amo", new Dictionary<string, string> { { "", "Latn"} } },
            { "an", new Dictionary<string, string> { { "", "Latn"} } },
            { "anp", new Dictionary<string, string> { { "", "Deva"} } },
            { "ar", new Dictionary<string, string> { { "", "Arab"}, { "IR", "Syrc"} } },
            { "arc", new Dictionary<string, string> { { "", "Armi"} } },
            { "arn", new Dictionary<string, string> { { "", "Latn"} } },
            { "arp", new Dictionary<string, string> { { "", "Latn"} } },
            { "arw", new Dictionary<string, string> { { "", "Latn"} } },
            { "as", new Dictionary<string, string> { { "", "Beng"} } },
            { "asa", new Dictionary<string, string> { { "", "Latn"} } },
            { "ast", new Dictionary<string, string> { { "", "Latn"} } },
            { "av", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "awa", new Dictionary<string, string> { { "", "Deva"} } },
            { "ay", new Dictionary<string, string> { { "", "Latn"} } },
            { "az", new Dictionary<string, string> { { "", "Latn"}, { "AZ", "Cyrl"}, { "IR", "Arab"} } },
            { "ba", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "bal", new Dictionary<string, string> { { "", "Arab"}, { "IR", "Latn"}, { "PK", "Latn"} } },
            { "ban", new Dictionary<string, string> { { "", "Latn"}, { "ID", "Bali"} } },
            { "bas", new Dictionary<string, string> { { "", "Latn"} } },
            { "bax", new Dictionary<string, string> { { "", "Bamu"} } },
            { "bbc", new Dictionary<string, string> { { "", "Latn"}, { "ID", "Batk"} } },
            { "be", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "bej", new Dictionary<string, string> { { "", "Arab"} } },
            { "bem", new Dictionary<string, string> { { "", "Latn"} } },
            { "bez", new Dictionary<string, string> { { "", "Latn"} } },
            { "bfq", new Dictionary<string, string> { { "", "Taml"} } },
            { "bft", new Dictionary<string, string> { { "", "Arab"} } },
            { "bfy", new Dictionary<string, string> { { "", "Deva"} } },
            { "bg", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "bh", new Dictionary<string, string> { { "", "Deva"} } },
            { "bhb", new Dictionary<string, string> { { "", "Deva"} } },
            { "bho", new Dictionary<string, string> { { "", "Deva"} } },
            { "bi", new Dictionary<string, string> { { "", "Latn"} } },
            { "bik", new Dictionary<string, string> { { "", "Latn"} } },
            { "bin", new Dictionary<string, string> { { "", "Latn"} } },
            { "bjj", new Dictionary<string, string> { { "", "Deva"} } },
            { "bku", new Dictionary<string, string> { { "", "Latn"} } },
            { "bla", new Dictionary<string, string> { { "", "Latn"} } },
            { "blt", new Dictionary<string, string> { { "", "Tavt"} } },
            { "bm", new Dictionary<string, string> { { "", "Latn"} } },
            { "bn", new Dictionary<string, string> { { "", "Beng"} } },
            { "bo", new Dictionary<string, string> { { "", "Tibt"} } },
            { "bqv", new Dictionary<string, string> { { "", "Latn"} } },
            { "br", new Dictionary<string, string> { { "", "Latn"} } },
            { "bra", new Dictionary<string, string> { { "", "Deva"} } },
            { "brx", new Dictionary<string, string> { { "", "Deva"} } },
            { "bs", new Dictionary<string, string> { { "", "Latn"} } },
            { "btv", new Dictionary<string, string> { { "", "Deva"} } },
            { "bua", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "buc", new Dictionary<string, string> { { "", "Latn"} } },
            { "bug", new Dictionary<string, string> { { "", "Latn"}, { "ID", "Bugi"} } },
            { "bya", new Dictionary<string, string> { { "", "Latn"} } },
            { "byn", new Dictionary<string, string> { { "", "Ethi"} } },
            { "ca", new Dictionary<string, string> { { "", "Latn"} } },
            { "cad", new Dictionary<string, string> { { "", "Latn"} } },
            { "car", new Dictionary<string, string> { { "", "Latn"} } },
            { "cay", new Dictionary<string, string> { { "", "Latn"} } },
            { "cch", new Dictionary<string, string> { { "", "Latn"} } },
            { "ccp", new Dictionary<string, string> { { "", "Beng"} } },
            { "ce", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "ceb", new Dictionary<string, string> { { "", "Latn"} } },
            { "cgg", new Dictionary<string, string> { { "", "Latn"} } },
            { "ch", new Dictionary<string, string> { { "", "Latn"} } },
            { "chk", new Dictionary<string, string> { { "", "Latn"} } },
            { "chm", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "chn", new Dictionary<string, string> { { "", "Latn"} } },
            { "cho", new Dictionary<string, string> { { "", "Latn"} } },
            { "chp", new Dictionary<string, string> { { "", "Latn"} } },
            { "chr", new Dictionary<string, string> { { "", "Cher"} } },
            { "chy", new Dictionary<string, string> { { "", "Latn"} } },
            { "cja", new Dictionary<string, string> { { "", "Arab"} } },
            { "cjm", new Dictionary<string, string> { { "", "Cham"} } },
            { "cjs", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "ckb", new Dictionary<string, string> { { "", "Arab"} } },
            { "ckt", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "co", new Dictionary<string, string> { { "", "Latn"} } },
            { "cop", new Dictionary<string, string> { { "", "Arab"} } },
            { "cpe", new Dictionary<string, string> { { "", "Latn"} } },
            { "cr", new Dictionary<string, string> { { "", "Cans"} } },
            { "crh", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "crk", new Dictionary<string, string> { { "", "Cans"} } },
            { "cs", new Dictionary<string, string> { { "", "Latn"} } },
            { "csb", new Dictionary<string, string> { { "", "Latn"} } },
            { "cu", new Dictionary<string, string> { { "", "Glag"} } },
            { "cv", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "cy", new Dictionary<string, string> { { "", "Latn"} } },
            { "da", new Dictionary<string, string> { { "", "Latn"} } },
            { "dak", new Dictionary<string, string> { { "", "Latn"} } },
            { "dar", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "dav", new Dictionary<string, string> { { "", "Latn"} } },
            { "de", new Dictionary<string, string> { { "", "Latn"}, { "BR", "Runr"}, { "KZ", "Runr"}, { "US", "Runr"} } },
            { "del", new Dictionary<string, string> { { "", "Latn"} } },
            { "den", new Dictionary<string, string> { { "", "Latn"} } },
            { "dgr", new Dictionary<string, string> { { "", "Latn"} } },
            { "din", new Dictionary<string, string> { { "", "Latn"} } },
            { "dje", new Dictionary<string, string> { { "", "Latn"} } },
            { "dng", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "doi", new Dictionary<string, string> { { "", "Arab"} } },
            { "dsb", new Dictionary<string, string> { { "", "Latn"} } },
            { "dua", new Dictionary<string, string> { { "", "Latn"} } },
            { "dv", new Dictionary<string, string> { { "", "Thaa"} } },
            { "dyo", new Dictionary<string, string> { { "", "Arab"} } },
            { "dyu", new Dictionary<string, string> { { "", "Latn"} } },
            { "dz", new Dictionary<string, string> { { "", "Tibt"} } },
            { "ebu", new Dictionary<string, string> { { "", "Latn"} } },
            { "ee", new Dictionary<string, string> { { "", "Latn"} } },
            { "efi", new Dictionary<string, string> { { "", "Latn"} } },
            { "egy", new Dictionary<string, string> { { "", "Egyp"} } },
            { "eka", new Dictionary<string, string> { { "", "Latn"} } },
            { "eky", new Dictionary<string, string> { { "", "Kali"} } },
            { "el", new Dictionary<string, string> { { "", "Grek"} } },
            { "en", new Dictionary<string, string> { { "", "Latn"} } },
            { "eo", new Dictionary<string, string> { { "", "Latn"} } },
            { "es", new Dictionary<string, string> { { "", "Latn"} } },
            { "et", new Dictionary<string, string> { { "", "Latn"} } },
            { "ett", new Dictionary<string, string> { { "", "Ital"} } },
            { "eu", new Dictionary<string, string> { { "", "Latn"} } },
            { "evn", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "ewo", new Dictionary<string, string> { { "", "Latn"} } },
            { "fa", new Dictionary<string, string> { { "", "Arab"} } },
            { "fan", new Dictionary<string, string> { { "", "Latn"} } },
            { "ff", new Dictionary<string, string> { { "", "Latn"} } },
            { "fi", new Dictionary<string, string> { { "", "Latn"} } },
            { "fil", new Dictionary<string, string> { { "", "Latn"}, { "US", "Tglg"} } },
            { "fiu", new Dictionary<string, string> { { "", "Latn"} } },
            { "fj", new Dictionary<string, string> { { "", "Latn"} } },
            { "fo", new Dictionary<string, string> { { "", "Latn"} } },
            { "fon", new Dictionary<string, string> { { "", "Latn"} } },
            { "fr", new Dictionary<string, string> { { "", "Latn"} } },
            { "frr", new Dictionary<string, string> { { "", "Latn"} } },
            { "frs", new Dictionary<string, string> { { "", "Latn"} } },
            { "fur", new Dictionary<string, string> { { "", "Latn"} } },
            { "fy", new Dictionary<string, string> { { "", "Latn"} } },
            { "ga", new Dictionary<string, string> { { "", "Latn"} } },
            { "gaa", new Dictionary<string, string> { { "", "Latn"} } },
            { "gag", new Dictionary<string, string> { { "", "Latn"}, { "MD", "Cyrl"} } },
            { "gay", new Dictionary<string, string> { { "", "Latn"} } },
            { "gba", new Dictionary<string, string> { { "", "Arab"} } },
            { "gbm", new Dictionary<string, string> { { "", "Deva"} } },
            { "gcr", new Dictionary<string, string> { { "", "Latn"} } },
            { "gd", new Dictionary<string, string> { { "", "Latn"} } },
            { "gez", new Dictionary<string, string> { { "", "Ethi"} } },
            { "gil", new Dictionary<string, string> { { "", "Latn"} } },
            { "gl", new Dictionary<string, string> { { "", "Latn"} } },
            { "gld", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "gn", new Dictionary<string, string> { { "", "Latn"} } },
            { "gon", new Dictionary<string, string> { { "", "Telu"} } },
            { "gor", new Dictionary<string, string> { { "", "Latn"} } },
            { "got", new Dictionary<string, string> { { "", "Goth"} } },
            { "grb", new Dictionary<string, string> { { "", "Latn"} } },
            { "grc", new Dictionary<string, string> { { "", "Cprt"} } },
            { "grt", new Dictionary<string, string> { { "", "Beng"} } },
            { "gsw", new Dictionary<string, string> { { "", "Latn"} } },
            { "gu", new Dictionary<string, string> { { "", "Gujr"} } },
            { "guz", new Dictionary<string, string> { { "", "Latn"} } },
            { "gv", new Dictionary<string, string> { { "", "Latn"} } },
            { "gwi", new Dictionary<string, string> { { "", "Latn"} } },
            { "ha", new Dictionary<string, string> { { "", "Arab"}, { "NE", "Latn"}, { "GH", "Latn"} } },
            { "hai", new Dictionary<string, string> { { "", "Latn"} } },
            { "haw", new Dictionary<string, string> { { "", "Latn"} } },
            { "he", new Dictionary<string, string> { { "", "Hebr"} } },
            { "hi", new Dictionary<string, string> { { "", "Deva"} } },
            { "hil", new Dictionary<string, string> { { "", "Latn"} } },
            { "hit", new Dictionary<string, string> { { "", "Xsux"} } },
            { "hmn", new Dictionary<string, string> { { "", "Latn"} } },
            { "hne", new Dictionary<string, string> { { "", "Deva"} } },
            { "hnn", new Dictionary<string, string> { { "", "Latn"} } },
            { "ho", new Dictionary<string, string> { { "", "Latn"} } },
            { "hoc", new Dictionary<string, string> { { "", "Deva"} } },
            { "hoj", new Dictionary<string, string> { { "", "Deva"} } },
            { "hop", new Dictionary<string, string> { { "", "Latn"} } },
            { "hr", new Dictionary<string, string> { { "", "Latn"} } },
            { "hsb", new Dictionary<string, string> { { "", "Latn"} } },
            { "ht", new Dictionary<string, string> { { "", "Latn"} } },
            { "hu", new Dictionary<string, string> { { "", "Latn"} } },
            { "hup", new Dictionary<string, string> { { "", "Latn"} } },
            { "hy", new Dictionary<string, string> { { "", "Armn"} } },
            { "hz", new Dictionary<string, string> { { "", "Latn"} } },
            { "ia", new Dictionary<string, string> { { "", "Latn"} } },
            { "iba", new Dictionary<string, string> { { "", "Latn"} } },
            { "ibb", new Dictionary<string, string> { { "", "Latn"} } },
            { "id", new Dictionary<string, string> { { "", "Latn"} } },
            { "ig", new Dictionary<string, string> { { "", "Latn"} } },
            { "ii", new Dictionary<string, string> { { "", "Yiii"}, { "CN", "Latn"} } },
            { "ik", new Dictionary<string, string> { { "", "Latn"} } },
            { "ilo", new Dictionary<string, string> { { "", "Latn"} } },
            { "inh", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "is", new Dictionary<string, string> { { "", "Latn"} } },
            { "it", new Dictionary<string, string> { { "", "Latn"} } },
            { "iu", new Dictionary<string, string> { { "", "Cans"}, { "CA", "Latn"} } },
            { "ja", new Dictionary<string, string> { { "", "Jpan"} } },
            { "jmc", new Dictionary<string, string> { { "", "Latn"} } },
            { "jpr", new Dictionary<string, string> { { "", "Hebr"} } },
            { "jrb", new Dictionary<string, string> { { "", "Hebr"} } },
            { "jv", new Dictionary<string, string> { { "", "Latn"}, { "ID", "Java"} } },
            { "ka", new Dictionary<string, string> { { "", "Geor"} } },
            { "kaa", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "kab", new Dictionary<string, string> { { "", "Latn"} } },
            { "kac", new Dictionary<string, string> { { "", "Latn"} } },
            { "kaj", new Dictionary<string, string> { { "", "Latn"} } },
            { "kam", new Dictionary<string, string> { { "", "Latn"} } },
            { "kbd", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "kca", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "kcg", new Dictionary<string, string> { { "", "Latn"} } },
            { "kde", new Dictionary<string, string> { { "", "Latn"} } },
            { "kdt", new Dictionary<string, string> { { "", "Thai"} } },
            { "kea", new Dictionary<string, string> { { "", "Latn"} } },
            { "kfo", new Dictionary<string, string> { { "", "Latn"} } },
            { "kfr", new Dictionary<string, string> { { "", "Deva"} } },
            { "kg", new Dictionary<string, string> { { "", "Latn"} } },
            { "kha", new Dictionary<string, string> { { "", "Latn"}, { "IN", "Beng"} } },
            { "khb", new Dictionary<string, string> { { "", "Talu"} } },
            { "khq", new Dictionary<string, string> { { "", "Latn"} } },
            { "kht", new Dictionary<string, string> { { "", "Mymr"} } },
            { "ki", new Dictionary<string, string> { { "", "Latn"} } },
            { "kj", new Dictionary<string, string> { { "", "Latn"} } },
            { "kjh", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "kk", new Dictionary<string, string> { { "", "Arab"}, { "KZ", "Cyrl"}, { "TR", "Cyrl"} } },
            { "kl", new Dictionary<string, string> { { "", "Latn"} } },
            { "kln", new Dictionary<string, string> { { "", "Latn"} } },
            { "km", new Dictionary<string, string> { { "", "Khmr"} } },
            { "kmb", new Dictionary<string, string> { { "", "Latn"} } },
            { "kn", new Dictionary<string, string> { { "", "Knda"} } },
            { "ko", new Dictionary<string, string> { { "", "Kore"} } },
            { "koi", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "kok", new Dictionary<string, string> { { "", "Deva"} } },
            { "kos", new Dictionary<string, string> { { "", "Latn"} } },
            { "kpe", new Dictionary<string, string> { { "", "Latn"} } },
            { "kpy", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "kr", new Dictionary<string, string> { { "", "Latn"} } },
            { "krc", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "kri", new Dictionary<string, string> { { "", "Latn"} } },
            { "krl", new Dictionary<string, string> { { "", "Latn"} } },
            { "kru", new Dictionary<string, string> { { "", "Deva"} } },
            { "ks", new Dictionary<string, string> { { "", "Arab"} } },
            { "ksb", new Dictionary<string, string> { { "", "Latn"} } },
            { "ksf", new Dictionary<string, string> { { "", "Latn"} } },
            { "ksh", new Dictionary<string, string> { { "", "Latn"} } },
            { "ku", new Dictionary<string, string> { { "", "Latn"}, { "LB", "Arab"} } },
            { "kum", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "kut", new Dictionary<string, string> { { "", "Latn"} } },
            { "kv", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "kw", new Dictionary<string, string> { { "", "Latn"} } },
            { "ky", new Dictionary<string, string> { { "", "Cyrl"}, { "CN", "Arab"}, { "TR", "Latn"} } },
            { "kyu", new Dictionary<string, string> { { "", "Kali"} } },
            { "la", new Dictionary<string, string> { { "", "Latn"} } },
            { "lad", new Dictionary<string, string> { { "", "Hebr"} } },
            { "lag", new Dictionary<string, string> { { "", "Latn"} } },
            { "lah", new Dictionary<string, string> { { "", "Arab"} } },
            { "lam", new Dictionary<string, string> { { "", "Latn"} } },
            { "lb", new Dictionary<string, string> { { "", "Latn"} } },
            { "lbe", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "lcp", new Dictionary<string, string> { { "", "Thai"} } },
            { "lep", new Dictionary<string, string> { { "", "Lepc"} } },
            { "lez", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "lg", new Dictionary<string, string> { { "", "Latn"} } },
            { "li", new Dictionary<string, string> { { "", "Latn"} } },
            { "lif", new Dictionary<string, string> { { "", "Deva"} } },
            { "lis", new Dictionary<string, string> { { "", "Lisu"} } },
            { "lki", new Dictionary<string, string> { { "", "Arab"} } },
            { "lmn", new Dictionary<string, string> { { "", "Telu"} } },
            { "ln", new Dictionary<string, string> { { "", "Latn"} } },
            { "lo", new Dictionary<string, string> { { "", "Laoo"} } },
            { "lol", new Dictionary<string, string> { { "", "Latn"} } },
            { "loz", new Dictionary<string, string> { { "", "Latn"} } },
            { "lt", new Dictionary<string, string> { { "", "Latn"} } },
            { "lu", new Dictionary<string, string> { { "", "Latn"} } },
            { "lua", new Dictionary<string, string> { { "", "Latn"} } },
            { "lui", new Dictionary<string, string> { { "", "Latn"} } },
            { "lun", new Dictionary<string, string> { { "", "Latn"} } },
            { "luo", new Dictionary<string, string> { { "", "Latn"} } },
            { "lus", new Dictionary<string, string> { { "", "Beng"} } },
            { "lut", new Dictionary<string, string> { { "", "Latn"} } },
            { "luy", new Dictionary<string, string> { { "", "Latn"} } },
            { "lv", new Dictionary<string, string> { { "", "Latn"} } },
            { "lwl", new Dictionary<string, string> { { "", "Thai"} } },
            { "mad", new Dictionary<string, string> { { "", "Latn"} } },
            { "mag", new Dictionary<string, string> { { "", "Deva"} } },
            { "mai", new Dictionary<string, string> { { "", "Deva"} } },
            { "mak", new Dictionary<string, string> { { "", "Latn"}, { "ID", "Bugi"} } },
            { "man", new Dictionary<string, string> { { "", "Latn"}, { "GN", "Nkoo"} } },
            { "mas", new Dictionary<string, string> { { "", "Latn"} } },
            { "mdf", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "mdh", new Dictionary<string, string> { { "", "Latn"} } },
            { "mdr", new Dictionary<string, string> { { "", "Latn"} } },
            { "men", new Dictionary<string, string> { { "", "Latn"} } },
            { "mer", new Dictionary<string, string> { { "", "Latn"} } },
            { "mfe", new Dictionary<string, string> { { "", "Latn"} } },
            { "mg", new Dictionary<string, string> { { "", "Latn"} } },
            { "mgh", new Dictionary<string, string> { { "", "Latn"} } },
            { "mh", new Dictionary<string, string> { { "", "Latn"} } },
            { "mi", new Dictionary<string, string> { { "", "Latn"} } },
            { "mic", new Dictionary<string, string> { { "", "Latn"} } },
            { "min", new Dictionary<string, string> { { "", "Latn"} } },
            { "mk", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "ml", new Dictionary<string, string> { { "", "Mlym"} } },
            { "mn", new Dictionary<string, string> { { "", "Cyrl"}, { "CN", "Mong"} } },
            { "mnc", new Dictionary<string, string> { { "", "Mong"} } },
            { "mni", new Dictionary<string, string> { { "", "Beng"}, { "IN", "Mtei"} } },
            { "mns", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "mnw", new Dictionary<string, string> { { "", "Mymr"} } },
            { "moh", new Dictionary<string, string> { { "", "Latn"} } },
            { "mos", new Dictionary<string, string> { { "", "Latn"} } },
            { "mr", new Dictionary<string, string> { { "", "Deva"} } },
            { "ms", new Dictionary<string, string> { { "", "Arab"}, { "MY", "Latn"}, { "SG", "Latn"} } },
            { "mt", new Dictionary<string, string> { { "", "Latn"} } },
            { "mua", new Dictionary<string, string> { { "", "Latn"} } },
            { "mus", new Dictionary<string, string> { { "", "Latn"} } },
            { "mwl", new Dictionary<string, string> { { "", "Latn"} } },
            { "mwr", new Dictionary<string, string> { { "", "Deva"} } },
            { "my", new Dictionary<string, string> { { "", "Mymr"} } },
            { "myv", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "myz", new Dictionary<string, string> { { "", "Mand"} } },
            { "na", new Dictionary<string, string> { { "", "Latn"} } },
            { "nap", new Dictionary<string, string> { { "", "Latn"} } },
            { "naq", new Dictionary<string, string> { { "", "Latn"} } },
            { "nb", new Dictionary<string, string> { { "", "Latn"} } },
            { "nd", new Dictionary<string, string> { { "", "Latn"} } },
            { "nds", new Dictionary<string, string> { { "", "Latn"} } },
            { "ne", new Dictionary<string, string> { { "", "Deva"} } },
            { "new", new Dictionary<string, string> { { "", "Deva"} } },
            { "ng", new Dictionary<string, string> { { "", "Latn"} } },
            { "nia", new Dictionary<string, string> { { "", "Latn"} } },
            { "nij", new Dictionary<string, string> { { "", ""} } },
            { "niu", new Dictionary<string, string> { { "", "Latn"} } },
            { "nl", new Dictionary<string, string> { { "", "Latn"} } },
            { "nmg", new Dictionary<string, string> { { "", "Latn"} } },
            { "nn", new Dictionary<string, string> { { "", "Latn"} } },
            { "nnh", new Dictionary<string, string> { { "", ""} } },
            { "nod", new Dictionary<string, string> { { "", "Lana"} } },
            { "noe", new Dictionary<string, string> { { "", ""} } },
            { "nog", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "nqo", new Dictionary<string, string> { { "", "Nkoo"} } },
            { "nr", new Dictionary<string, string> { { "", "Latn"} } },
            { "nsk", new Dictionary<string, string> { { "", ""} } },
            { "nso", new Dictionary<string, string> { { "", "Latn"} } },
            { "nus", new Dictionary<string, string> { { "", "Latn"} } },
            { "nv", new Dictionary<string, string> { { "", "Latn"} } },
            { "ny", new Dictionary<string, string> { { "", "Latn"} } },
            { "nym", new Dictionary<string, string> { { "", "Latn"} } },
            { "nyn", new Dictionary<string, string> { { "", "Latn"} } },
            { "nyo", new Dictionary<string, string> { { "", "Latn"} } },
            { "nzi", new Dictionary<string, string> { { "", "Latn"} } },
            { "oc", new Dictionary<string, string> { { "", "Latn"} } },
            { "oj", new Dictionary<string, string> { { "", "Cans"} } },
            { "om", new Dictionary<string, string> { { "", "Latn"}, { "ET", "Ethi"} } },
            { "or", new Dictionary<string, string> { { "", "Orya"} } },
            { "os", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "osa", new Dictionary<string, string> { { "", "Latn"} } },
            { "osc", new Dictionary<string, string> { { "", "Ital"} } },
            { "otk", new Dictionary<string, string> { { "", "Orkh"} } },
            { "pa", new Dictionary<string, string> { { "", "Guru"}, { "PK", "Arab"} } },
            { "pag", new Dictionary<string, string> { { "", "Latn"} } },
            { "pal", new Dictionary<string, string> { { "", "Phli"} } },
            { "pam", new Dictionary<string, string> { { "", "Latn"} } },
            { "pap", new Dictionary<string, string> { { "", "Latn"} } },
            { "pau", new Dictionary<string, string> { { "", "Latn"} } },
            { "peo", new Dictionary<string, string> { { "", "Xpeo"} } },
            { "phn", new Dictionary<string, string> { { "", "Phnx"} } },
            { "pi", new Dictionary<string, string> { { "", "Deva"} } },
            { "pko", new Dictionary<string, string> { { "", ""} } },
            { "pl", new Dictionary<string, string> { { "", "Latn"} } },
            { "pon", new Dictionary<string, string> { { "", "Latn"} } },
            { "pra", new Dictionary<string, string> { { "", "Brah"} } },
            { "prd", new Dictionary<string, string> { { "", "Arab"} } },
            { "prg", new Dictionary<string, string> { { "", "Latn"} } },
            { "prs", new Dictionary<string, string> { { "", "Arab"} } },
            { "ps", new Dictionary<string, string> { { "", "Arab"} } },
            { "pt", new Dictionary<string, string> { { "", "Latn"} } },
            { "puu", new Dictionary<string, string> { { "", ""} } },
            { "qu", new Dictionary<string, string> { { "", "Latn"} } },
            { "raj", new Dictionary<string, string> { { "", "Latn"} } },
            { "rap", new Dictionary<string, string> { { "", "Latn"} } },
            { "rar", new Dictionary<string, string> { { "", "Latn"} } },
            { "rcf", new Dictionary<string, string> { { "", "Latn"} } },
            { "rej", new Dictionary<string, string> { { "", "Latn"}, { "ID", "Rjng"} } },
            { "ria", new Dictionary<string, string> { { "", ""} } },
            { "rif", new Dictionary<string, string> { { "", ""} } },
            { "rjs", new Dictionary<string, string> { { "", "Deva"} } },
            { "rkt", new Dictionary<string, string> { { "", "Beng"} } },
            { "rm", new Dictionary<string, string> { { "", "Latn"} } },
            { "rmf", new Dictionary<string, string> { { "", ""} } },
            { "rmo", new Dictionary<string, string> { { "", ""} } },
            { "rmt", new Dictionary<string, string> { { "", ""} } },
            { "rn", new Dictionary<string, string> { { "", "Latn"} } },
            { "rng", new Dictionary<string, string> { { "", ""} } },
            { "ro", new Dictionary<string, string> { { "", "Latn"}, { "RS", "Cyrl"} } },
            { "rob", new Dictionary<string, string> { { "", ""} } },
            { "rof", new Dictionary<string, string> { { "", "Latn"} } },
            { "rom", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "ru", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "rue", new Dictionary<string, string> { { "", ""} } },
            { "rup", new Dictionary<string, string> { { "", "Latn"} } },
            { "rw", new Dictionary<string, string> { { "", "Latn"} } },
            { "rwk", new Dictionary<string, string> { { "", "Latn"} } },
            { "ryu", new Dictionary<string, string> { { "", ""} } },
            { "sa", new Dictionary<string, string> { { "", "Deva"} } },
            { "sad", new Dictionary<string, string> { { "", "Latn"} } },
            { "saf", new Dictionary<string, string> { { "", "Latn"} } },
            { "sah", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "sam", new Dictionary<string, string> { { "", "Hebr"} } },
            { "saq", new Dictionary<string, string> { { "", "Latn"} } },
            { "sas", new Dictionary<string, string> { { "", "Latn"} } },
            { "sat", new Dictionary<string, string> { { "", "Latn"} } },
            { "saz", new Dictionary<string, string> { { "", "Saur"} } },
            { "sbp", new Dictionary<string, string> { { "", "Latn"} } },
            { "sc", new Dictionary<string, string> { { "", "Latn"} } },
            { "sck", new Dictionary<string, string> { { "", ""} } },
            { "scn", new Dictionary<string, string> { { "", "Latn"} } },
            { "sco", new Dictionary<string, string> { { "", "Latn"} } },
            { "scs", new Dictionary<string, string> { { "", ""} } },
            { "sd", new Dictionary<string, string> { { "", "Arab"}, { "IN", "Deva"} } },
            { "sdh", new Dictionary<string, string> { { "", "Arab"} } },
            { "se", new Dictionary<string, string> { { "", "Latn"}, { "NO", "Cyrl"} } },
            { "see", new Dictionary<string, string> { { "", "Latn"} } },
            { "sef", new Dictionary<string, string> { { "", ""} } },
            { "seh", new Dictionary<string, string> { { "", "Latn"} } },
            { "sel", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "ses", new Dictionary<string, string> { { "", "Latn"} } },
            { "sg", new Dictionary<string, string> { { "", "Latn"} } },
            { "sga", new Dictionary<string, string> { { "", "Latn"} } },
            { "shi", new Dictionary<string, string> { { "", "Tfng"} } },
            { "shn", new Dictionary<string, string> { { "", "Mymr"} } },
            { "si", new Dictionary<string, string> { { "", "Sinh"} } },
            { "sid", new Dictionary<string, string> { { "", "Latn"} } },
            { "sk", new Dictionary<string, string> { { "", "Latn"} } },
            { "skr", new Dictionary<string, string> { { "", ""} } },
            { "sl", new Dictionary<string, string> { { "", "Latn"} } },
            { "sm", new Dictionary<string, string> { { "", "Latn"} } },
            { "sma", new Dictionary<string, string> { { "", "Latn"} } },
            { "smi", new Dictionary<string, string> { { "", "Latn"} } },
            { "smj", new Dictionary<string, string> { { "", "Latn"} } },
            { "smn", new Dictionary<string, string> { { "", "Latn"} } },
            { "sms", new Dictionary<string, string> { { "", "Latn"} } },
            { "sn", new Dictionary<string, string> { { "", "Latn"} } },
            { "snk", new Dictionary<string, string> { { "", "Latn"} } },
            { "so", new Dictionary<string, string> { { "", "Latn"} } },
            { "son", new Dictionary<string, string> { { "", "Latn"} } },
            { "sou", new Dictionary<string, string> { { "", ""} } },
            { "sq", new Dictionary<string, string> { { "", "Latn"} } },
            { "sr", new Dictionary<string, string> { { "", "Latn"} } },
            { "srn", new Dictionary<string, string> { { "", "Latn"} } },
            { "srr", new Dictionary<string, string> { { "", "Latn"} } },
            { "srx", new Dictionary<string, string> { { "", ""} } },
            { "ss", new Dictionary<string, string> { { "", "Latn"} } },
            { "ssy", new Dictionary<string, string> { { "", "Latn"} } },
            { "st", new Dictionary<string, string> { { "", "Latn"} } },
            { "su", new Dictionary<string, string> { { "", "Latn"} } },
            { "suk", new Dictionary<string, string> { { "", "Latn"} } },
            { "sus", new Dictionary<string, string> { { "", "Latn"}, { "GN", "Arab"} } },
            { "sv", new Dictionary<string, string> { { "", "Latn"} } },
            { "sw", new Dictionary<string, string> { { "", "Latn"} } },
            { "swb", new Dictionary<string, string> { { "", "Arab"}, { "YT", "Latn"} } },
            { "swc", new Dictionary<string, string> { { "", "Latn"} } },
            { "swv", new Dictionary<string, string> { { "", ""} } },
            { "sxn", new Dictionary<string, string> { { "", ""} } },
            { "syi", new Dictionary<string, string> { { "", ""} } },
            { "syl", new Dictionary<string, string> { { "", "Beng"}, { "BD", "Sylo"} } },
            { "syr", new Dictionary<string, string> { { "", "Syrc"} } },
            { "ta", new Dictionary<string, string> { { "", "Taml"} } },
            { "tab", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "taj", new Dictionary<string, string> { { "", ""} } },
            { "tbw", new Dictionary<string, string> { { "", "Latn"} } },
            { "tcy", new Dictionary<string, string> { { "", "Knda"} } },
            { "tdd", new Dictionary<string, string> { { "", "Tale"} } },
            { "tdg", new Dictionary<string, string> { { "", ""} } },
            { "tdh", new Dictionary<string, string> { { "", ""} } },
            { "te", new Dictionary<string, string> { { "", "Telu"} } },
            { "tem", new Dictionary<string, string> { { "", "Latn"} } },
            { "teo", new Dictionary<string, string> { { "", "Latn"} } },
            { "ter", new Dictionary<string, string> { { "", "Latn"} } },
            { "tet", new Dictionary<string, string> { { "", "Latn"} } },
            { "tg", new Dictionary<string, string> { { "", "Cyrl"}, { "PK", "Arab"} } },
            { "th", new Dictionary<string, string> { { "", "Thai"} } },
            { "thl", new Dictionary<string, string> { { "", ""} } },
            { "thq", new Dictionary<string, string> { { "", ""} } },
            { "thr", new Dictionary<string, string> { { "", ""} } },
            { "ti", new Dictionary<string, string> { { "", "Ethi"} } },
            { "tig", new Dictionary<string, string> { { "", "Ethi"} } },
            { "tiv", new Dictionary<string, string> { { "", "Latn"} } },
            { "tk", new Dictionary<string, string> { { "", "Latn"} } },
            { "tkl", new Dictionary<string, string> { { "", "Latn"} } },
            { "tkt", new Dictionary<string, string> { { "", ""} } },
            { "tli", new Dictionary<string, string> { { "", "Latn"} } },
            { "tmh", new Dictionary<string, string> { { "", "Latn"} } },
            { "tn", new Dictionary<string, string> { { "", "Latn"} } },
            { "to", new Dictionary<string, string> { { "", "Latn"} } },
            { "tog", new Dictionary<string, string> { { "", "Latn"} } },
            { "tpi", new Dictionary<string, string> { { "", "Latn"} } },
            { "tr", new Dictionary<string, string> { { "", "Latn"}, { "DE", "Arab"}, { "MK", "Arab"} } },
            { "tru", new Dictionary<string, string> { { "", "Latn"} } },
            { "trv", new Dictionary<string, string> { { "", "Latn"} } },
            { "ts", new Dictionary<string, string> { { "", "Latn"} } },
            { "tsf", new Dictionary<string, string> { { "", ""} } },
            { "tsg", new Dictionary<string, string> { { "", "Latn"} } },
            { "tsi", new Dictionary<string, string> { { "", "Latn"} } },
            { "tsj", new Dictionary<string, string> { { "", ""} } },
            { "tt", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "ttj", new Dictionary<string, string> { { "", ""} } },
            { "tts", new Dictionary<string, string> { { "", "Thai"} } },
            { "tum", new Dictionary<string, string> { { "", "Latn"} } },
            { "tut", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "tvl", new Dictionary<string, string> { { "", "Latn"} } },
            { "twq", new Dictionary<string, string> { { "", "Latn"} } },
            { "ty", new Dictionary<string, string> { { "", "Latn"} } },
            { "tyv", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "tzm", new Dictionary<string, string> { { "", "Latn"} } },
            { "ude", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "udm", new Dictionary<string, string> { { "", "Cyrl"}, { "RU", "Latn"} } },
            { "ug", new Dictionary<string, string> { { "", "Arab"}, { "KZ", "Cyrl"}, { "MN", "Cyrl"} } },
            { "uga", new Dictionary<string, string> { { "", "Ugar"} } },
            { "uk", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "uli", new Dictionary<string, string> { { "", "Latn"} } },
            { "umb", new Dictionary<string, string> { { "", "Latn"} } },
            { "unr", new Dictionary<string, string> { { "", "Beng"}, { "NP", "Deva"} } },
            { "unx", new Dictionary<string, string> { { "", "Beng"} } },
            { "ur", new Dictionary<string, string> { { "", "Arab"} } },
            { "uz", new Dictionary<string, string> { { "", "Latn"}, { "AF", "Arab"}, { "CN", "Cyrl"} } },
            { "vai", new Dictionary<string, string> { { "", "Vaii"} } },
            { "ve", new Dictionary<string, string> { { "", "Latn"} } },
            { "vi", new Dictionary<string, string> { { "", "Latn"}, { "US", "Hani"} } },
            { "vo", new Dictionary<string, string> { { "", "Latn"} } },
            { "vot", new Dictionary<string, string> { { "", "Latn"} } },
            { "vun", new Dictionary<string, string> { { "", "Latn"} } },
            { "wa", new Dictionary<string, string> { { "", "Latn"} } },
            { "wae", new Dictionary<string, string> { { "", "Latn"} } },
            { "wak", new Dictionary<string, string> { { "", "Latn"} } },
            { "wal", new Dictionary<string, string> { { "", "Ethi"} } },
            { "war", new Dictionary<string, string> { { "", "Latn"} } },
            { "was", new Dictionary<string, string> { { "", "Latn"} } },
            { "wo", new Dictionary<string, string> { { "", "Latn"} } },
            { "xal", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "xcr", new Dictionary<string, string> { { "", "Cari"} } },
            { "xh", new Dictionary<string, string> { { "", "Latn"} } },
            { "xog", new Dictionary<string, string> { { "", "Latn"} } },
            { "xpr", new Dictionary<string, string> { { "", "Prti"} } },
            { "xsa", new Dictionary<string, string> { { "", "Sarb"} } },
            { "xsr", new Dictionary<string, string> { { "", "Deva"} } },
            { "xum", new Dictionary<string, string> { { "", "Ital"} } },
            { "yao", new Dictionary<string, string> { { "", "Latn"} } },
            { "yap", new Dictionary<string, string> { { "", "Latn"} } },
            { "yav", new Dictionary<string, string> { { "", "Latn"} } },
            { "yi", new Dictionary<string, string> { { "", "Hebr"} } },
            { "yo", new Dictionary<string, string> { { "", "Latn"} } },
            { "yrk", new Dictionary<string, string> { { "", "Cyrl"} } },
            { "yue", new Dictionary<string, string> { { "", "Hans"} } },
            { "za", new Dictionary<string, string> { { "", "Latn"}, { "CN", "Hans"} } },
            { "zap", new Dictionary<string, string> { { "", "Latn"} } },
            { "zen", new Dictionary<string, string> { { "", "Tfng"} } },
            { "zh", new Dictionary<string, string> { { "", "Hant"}, { "CN", "Hans"}, { "HK", "Hans"}, { "MO", "Hans"}, { "SG", "Hans"}, { "MN", "Hans"} } },
            { "zu", new Dictionary<string, string> { { "", "Latn"} } },
            { "zun", new Dictionary<string, string> { { "", "Latn"} } },
            { "zza", new Dictionary<string, string> { { "", "Arab"} } }
        }.ToImmutableDictionary();
}